from extra_views.advanced import CreateWithInlinesView, UpdateWithInlinesView
from extra_views.formsets import InlineFormSet, GenericInlineFormSet
from extra_views.views import FormSetView, ModelFormSetView, InlineFormSetView, GenericInlineFormSetView
